SUPABASE_URL = "postgresql://postgres:Shuai621521!@db.cefgunrmpioptvvvkqwu.supabase.co:5432/postgres"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlZmd1bnJtcGlvcHR2dnZrcXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4MTYxNTQsImV4cCI6MjA4NTM5MjE1NH0.kAviMGhEJePXxoR4G3uoicPPLO0vHW6T-AzikyWWqmI"
